# @package __global__

defaults:
  - default
  - _self_

# Audio configuration
sample_rate: 48000  # Original sample rate
channels: 2  # Stereo
mono: false  # Don't mix to mono
resample: true  # Enable resampling
resample_rate: 24000  # Downsample to 24kHz

# Data source configuration
datasource:
  max_sample_rate: 48000
  max_channels: 2
  train: /home/alistairfraser/training_data/train.jsonl
  valid: /home/alistairfraser/training_data/valid.jsonl
  evaluate: /home/alistairfraser/training_data/evaluate.jsonl
  generate: /home/alistairfraser/training_data/generate.jsonl


# Dataset configuration
dataset:
  batch_size: 4  # Reduced batch size for 24GB GPUs
  num_workers: 4
  segment_duration: 1
  train:
    num_samples: 500000
    shuffle: true
  valid:
    num_samples: 10000
  evaluate:
    num_samples: 10000
  generate:
    num_samples: 50
    segment_duration: 10 